export const CLUSTER_LOAD_MODULE = 'CLUSTER_LOAD_MODULE';
export const CLUSTER_SPAWN_PROCESS = 'CLUSTER_SPAWN_PROCESS';

export const WORKER_LOAD_MODULE = 'WORKER_LOAD_MODULE';
export const WORKER_SPAWN_PROCESS = 'WORKER_SPAWN_PROCESS';

export const PROCESS_DIRECT_MESSAGE = 'PROCESS_DIRECT_MESSAGE';
export const PROCESS_PARENT_EXIT = 'PROCESS_PARENT_EXIT';
export const PROCESS_PROBE_STATE = 'PROCESS_PROBE_STATE';
